name: "MurphySec code scan"
description: "Software Supply Chain Security Scanning Tool"
author: "Wei Zhao <aweihooo@163.com>"
runs:
  using: "composite"
  steps:
    - run: |
        wget -q https://s.murphysec.com/release/install.sh -O - | /bin/bash
      shell: bash
    - run: murphysec  scan . --token ${{ secrets.MURPHYSEC_TOKEN }} --json >scan_results.json
    - run: | 
        wget https://s.murphysec.com/github_actions_format.py
        python3 github_actions_format.py
      shell: bash
    - run: |
        if [ -f "results.sarif" ]; then
          echo "file_exists=true" >> $GITHUB_ENV
        else
          echo "file_exists=false" >> $GITHUB_ENV
        fi
    if: env.file_exists == 'true'
    uses: github/codeql-action/upload-sarif@v2
    with:
      sarif_file: results.sarif
