name: "MurphySec code scan"
description: "Software Supply Chain Security Scanning Tool"
author: "Wei Zhao <aweihooo@163.com>"
branding:
  icon: 'alert-triangle'
  color: 'green'
inputs:
  MURPHYSEC_TOKEN:
    description: "The token should be filled in this field."
    default: test
runs:
  using: "composite"
  steps:
    - name: Checkout_Actions
      uses: actions/checkout@v3
    - run: wget -q https://s.murphysec.com/release/install.sh -O - | /bin/bash
      shell: bash
    - run: murphysec  scan . --token ${{ inputs.MURPHYSEC_TOKEN }} --json >scan_results.json
      shell: bash
    - run: wget https://s.murphysec.com/github_actions_format.py && python3 github_actions_format.py
      shell: bash
    - run: if [ -f "results.sarif" ]; then echo "file_exists=true" >> $GITHUB_ENV; else echo "file_exists=false" >> $GITHUB_ENV; fi
      shell: bash
    - name: Upload SARIF file
      if: env.file_exists == 'true'
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
