name: "MurphySec code scan"
description: "Software Supply Chain Security Scanning Tool"
author: "Wei Zhao <aweihooo@163.com>"
runs:
  uses: actions/checkout@v3
  run: |
    wget -q https://s.murphysec.com/release/install.sh -O - | /bin/bash
    run: murphysec  scan . --token $MURPHYSEC_TOKEN --json >scan_results.json
    run: | 
      wget https://s.murphysec.com/github_actions_format.py
      python3 github_actions_format.py
    run: |
      if [ -f "results.sarif" ]; then
        echo "file_exists=true" >> $GITHUB_ENV
      else
        echo "file_exists=false" >> $GITHUB_ENV
      fi
    if: env.file_exists == 'true'
    uses: github/codeql-action/upload-sarif@v2
    with:
      sarif_file: results.sarif
