name: "MurphySec code scan"
description: "Software Supply Chain Security Scanning Tool"
author: "Wei Zhao <aweihooo@163.com>"
inputs:
  MURPHYSEC_TOKEN: ${{ secrets.MURPHYSEC_TOKEN }}
runs:
  using: "composite"
  steps:
    - run: wget -q https://s.murphysec.com/release/install.sh -O - | /bin/bash
      shell: bash
    - run: echo ${{ inputs.MURPHYSEC_TOKEN }}
      shell: bash
    - run: wget https://s.murphysec.com/github_actions_format.py && python3 github_actions_format.py
      shell: bash
