pipeline { // 定义一个流水线
    agent any 

    stages { // 定义流水线中的各个阶段
        stage('Pull code') { // 定义一个名为 "Pull code" 的阶段，用于拉取项目代码
            steps { //使用 Git 插件从指定仓库拉取代码，指定凭据和仓库 URL
                git branch: 'main', credentialsId: '18d41658-xxxx-xxxx-xxxx-d8455f4e240b', url: 'https://xxx.xxx.com/root/xxx.git'
            }
        }
        stage("Build Project") { // 定义一个名为 "Build Project" 的阶段，用于构建项目
            steps {
                sh 'echo "Build Project"' // 在这里添加实际的构建命令
            }
        }
        stage('Code Scan') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'murphysec', variable: 'TOKEN')]) 
                    {
                        sh '''
                            murphysec scan . --token $TOKEN
                        '''
                    }
                    }
            }
        }
        stage("Test") { // 定义一个名为 "Test" 的阶段，用于测试项目
            steps {
                sh 'echo "Test"' // 在这里添加实际的测试命令
            }
        }
        stage("publish project") { // 定义一个名为 "publish project" 的阶段，用于发布项目
            steps {
                sh 'echo "publish project"' // 在这里添加实际的发布命令
            }
        }
    }
    post { // 定义构建完成后的操作
        success { // 构建成功时执行以下操作
            script {
                currentBuild.description = "\n 打包成功！"
                // sh '''
                //    DATE=`date "+%Y-%m-%d_%H:%M:%S"`
                //    sh /usr/local/script/feishu.sh "项目：'$JOB_NAME'\\n结果：打包成功！已触发发布流程\\n时间：'$DATE'\\n节点：'$NODE_NAME'"
                // '''
            }
        }

        failure { // 构建失败时执行以下操作
            script {
                currentBuild.description = "\n 打包失败！"
                // sh '''
                //     DATE=`date "+%Y-%m-%d_%H:%M:%S"`
                //     sh /usr/local/script/feishu.sh "项目：'$JOB_NAME'\\n结果：打包失败！\\n时间：'$DATE'\\n节点：'$NODE_NAME'\\n原因：项目中存在强烈建议修复组件！"
                // '''
            }
        }
    }
}
